name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Silleellie/pylint-github-action@v2.1
      with:
        lint-path: |
          main.py
          mods/gui.py
          mods/get_sat.py
          mods/import_sat.py
          mods/get_keps.py
        python-version: 3.11
        pylintrc-path: .pylintrc
        
        
