name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Silleellie/pylint-github-action@v2.1
      with:
        lint-path: |
          sat.py
          gui.py
          data/Sat_Info.py
        python-version: 3.11
        
        
